# INTACT example

The main application scenarios of INTACT are presented as below.

### Application1: Temporal integration

2D example-HeLa

In [1]:
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage 
    csv1 = os.path.join('data', 'HeLa', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'HeLa', 'tracking_time2.csv')
    output = os.path.join('data', 'HeLa')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        img_shape = [700, 1100],  
        spatial_shift = [[0,0],[0,0]],  
        temporal_shift = [0,31],
        mode = 'temporal',  
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

ModuleNotFoundError: No module named 'pulp'

3D example-CE

In [3]:
# 3D
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage
    csv1 = os.path.join('data', 'CE', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'CE', 'tracking_time2.csv')
    output = os.path.join('data', 'CE')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution=[11.0, 1.0, 1.0],
        img_shape = [35,512,708],   
        spatial_shift = [[0,0,0],[0,0,0]], 
        temporal_shift = [0,83],
        mode = 'temporal',    
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
  Tracklet 1: 5008 detections
  Tracklet 2: 21532 detections
  Reading time: 64.43 seconds

Step 2: Selecting common cells...
  Selection time: 0.01 seconds

Step 3: Find overlapping nodes...
  Found 2704 matching pairs
  Matching time: 7.15 seconds

Step 4 & 5: Solving fusion...

Fusion Step 4&5 Statistics
total_step4_5_time_sec: 0.4498
easy_subgraphs: 104, hard_subgraphs: 1, easy_total_nodes: 5439
 hard_id  nodes  matches  root_satisfied_matches  root_violated_matches  max_depth  branches_explored  flow_calls  certified               reason  time_flow_sec
       0    124        7                       0                      7          1                  5          29       True priority_queue_empty       0.279787
  Fusion time: 0.74 seconds

[Step 4&5] total_time_sec = 0.7367

Step 6: Creating fused tracklet...
  Fused tracklet has 23839 detections
 Fusion time: 0.18 seconds

Step 7: Start saving...
CSV file saved to: dat

### Application2: Spatial integration

2D example-Neu

In [1]:
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage
    csv1 = os.path.join('data', 'Neu', 'tracking_space1.csv')
    csv2 = os.path.join('data', 'Neu', 'tracking_space2.csv')
    output = os.path.join('data', 'Neu')
    
    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution=[1.0, 1.0],
        img_shape = [800,1280],   
        img_shape1 = [420,1280],
        img_shape2 = [420,1280],
        spatial_shift = [[0,0],[380,0]], 
        temporal_shift = [0,0],
        mode = 'spatial',  
        solver = 'bb',     # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
  Tracklet 1: 38930 detections
  Tracklet 2: 41622 detections
  Reading time: 10.05 seconds

Step 2: Selecting common cells...
  Selection time: 1.02 seconds

Step 3: Find overlapping nodes...
  Found 1012 matching pairs
  Matching time: 0.82 seconds

Step 4 & 5: Solving fusion...

Fusion Step 4&5 Statistics
total_step4_5_time_sec: 0.0980
easy_subgraphs: 604, hard_subgraphs: 0, easy_total_nodes: 6457
No hard subgraphs.
  Fusion time: 0.12 seconds

[Step 4&5] total_time_sec = 0.1196

Step 6: Creating fused tracklet...
  Fused tracklet has 75707 detections
 Fusion time: 0.82 seconds

Step 7: Start saving...
CSV file saved to: data/Neu/tracking_result_merged.csv
  Saving time: 2.71 seconds

Fusion Complete!


3D example-TRIF

In [1]:
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage
    csv1 = os.path.join('data', 'TRIF', 'tracking_space1.csv')
    csv2 = os.path.join('data', 'TRIF', 'tracking_space2.csv')
    output = os.path.join('data', 'TRIF')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution=[1.0, 1.0, 1.0], 
        img_shape = [496,936,483],    
        img_shape1 = [496,483,483],
        img_shape2 = [496,483,483],
        spatial_shift = [[0,0,0],[0,453,0]], 
        temporal_shift = [0,0],
        mode = 'spatial',  
        solver = 'bb',      # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
  Tracklet 1: 233977 detections
  Tracklet 2: 156892 detections
  Reading time: 251.08 seconds

Step 2: Selecting common cells...
  Selection time: 22.15 seconds

Step 3: Find overlapping nodes...
  Found 8963 matching pairs
  Matching time: 10.65 seconds

Step 4 & 5: Solving fusion...

Fusion Step 4&5 Statistics
total_step4_5_time_sec: 46.3637
easy_subgraphs: 1354, hard_subgraphs: 115, easy_total_nodes: 20468
 hard_id  nodes  matches  root_satisfied_matches  root_violated_matches  max_depth  branches_explored  flow_calls  certified                   reason  time_flow_sec
       0    210        0                       0                      0          0                  0           1       True     priority_queue_empty       0.049140
       1     42        2                       1                      1          0                  1           5       True     priority_queue_empty       0.011243
       2     43        2    

In [ ]:
# FISH1+time
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage 
    csv1 = os.path.join('data', 'HeLa', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'HeLa', 'tracking_time2.csv')
    output = os.path.join('data', 'HeLa')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution = [5.86, 1.0, 1.0], # FISH1
        img_shape = [180,960,960],    # FISH1
        spatial_shift = [[0,0,0],[0,0,0]],  
        temporal_shift = [0,40],
        mode = 'temporal',  
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH1/time/movieInfo_0_59.pkl
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH1/time/movieInfo_40_109.pkl
  Reading time: 374.72 seconds

Step 2: Selecting common cells...
  Selection time: 0.28 seconds

Step 3: Find overlapping nodes...
  Found 102570 matching pairs
  Matching time: 28.73 seconds

Step 4 & 5: Solving fusion...

Fusion Step 4&5 Statistics
total_step4_5_time_sec: 69.4198
easy_subgraphs: 6155, hard_subgraphs: 1551, easy_total_nodes: 117427
 hard_id  nodes  matches  root_satisfied_matches  root_violated_matches  max_depth  branches_explored  flow_calls  certified                   reason  time_flow_sec
       0    105       44                       7                     37         20   

In [1]:
# FISH1+space
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage 
    csv1 = os.path.join('data', 'HeLa', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'HeLa', 'tracking_time2.csv')
    output = os.path.join('data', 'HeLa')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution = [5.86, 1.0, 1.0], # FISH1
        img_shape = [180,960,960],    # FISH1
        img_shape1 = [180,960,490],
        img_shape2 = [180,960,490],
        spatial_shift = [[0,0,0],[0,0,470]], # 3D
        temporal_shift = [0,0],
        mode = 'spatial',  
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH1/space/movieInfo_space1.pkl
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH1/space/movieInfo_space2.pkl
  Reading time: 329.82 seconds

Step 2: Selecting common cells...
  Selection time: 17.39 seconds

Step 3: Find overlapping nodes...
  Found 0 matching pairs
  Matching time: 5.83 seconds

Step 4 & 5: Solving fusion...

Fusion Step 4&5 Statistics
total_step4_5_time_sec: 0.4124
easy_subgraphs: 4519, hard_subgraphs: 0, easy_total_nodes: 40681
No hard subgraphs.
  Fusion time: 0.74 seconds

[Step 4&5] total_time_sec = 0.7419

Step 6: Creating fused tracklet...
[[ 170  163 1359]
 [ 170  163 1360]
 [ 170  163 1361]
 ...
 [ 177  175 1363]
 [ 177  175 1364]
 [ 177  175 1365]]


ValueError: invalid entry in coordinates array

In [1]:
# FISH2+time
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage 
    csv1 = os.path.join('data', 'HeLa', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'HeLa', 'tracking_time2.csv')
    output = os.path.join('data', 'HeLa')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution = [5.0, 1.0, 1.0], # FISH2
        img_shape = [253,896,909],    # FISH2
        spatial_shift = [[0,0,0],[0,0,0]], # 3D
        temporal_shift = [0,40],
        mode = 'temporal',  
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH2/time/movieInfo_300_359.pkl
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH2/time/movieInfo_340_399.pkl

[movieInfo1 after reading]
  detections: 915972
  frames range: [0, 59]
  xCoord range: [41.341, 899.139]
  yCoord range: [41.405, 862.011]
  zCoord range: [13.468, 234.034]

[movieInfo2 after reading]
  detections: 976615
  frames range: [0, 59]
  xCoord range: [41.663, 900.087]
  yCoord range: [40.788, 861.750]
  zCoord range: [13.468, 234.267]
  Reading time: 819.80 seconds

Step 2: Selecting common cells...

[movieInfo1_partial after reading]
  detections: 330490
  frames range: [39, 59]
  xCoord range: [42.120, 899.139]
  yCoord range: [41.648, 861.360]
  zCoord range: [13.468, 234.034]

In [1]:
# FISH2+space
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage 
    csv1 = os.path.join('data', 'HeLa', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'HeLa', 'tracking_time2.csv')
    output = os.path.join('data', 'HeLa')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution = [5.0, 1.0, 1.0], # FISH2
        img_shape = [253,896,909],    # FISH2
        img_shape1 = [253,458,909],
        img_shape2 = [253,458,909],
        spatial_shift = [[0,0,0],[0,438,0]], # 3D
        temporal_shift = [0,0],
        mode = 'spatial',  
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH2/space/movieInfo_space1.pkl
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/FISH2/space/movieInfo_space2.pkl

[movieInfo1 after reading]
  detections: 737609
  frames range: [0, 99]
  xCoord range: [41.341, 900.087]
  yCoord range: [40.788, 458.000]
  zCoord range: [13.468, 234.299]

[movieInfo2 after reading]
  detections: 885910
  frames range: [0, 99]
  xCoord range: [41.663, 871.484]
  yCoord range: [1.255, 424.011]
  zCoord range: [16.691, 234.267]
  Reading time: 695.65 seconds

Step 2: Selecting common cells...

[movieInfo1_partial after reading]
  detections: 30790
  frames range: [0, 99]
  xCoord range: [42.361, 868.293]
  yCoord range: [109.089, 140.262]
  zCoord range: [16.691, 234.088]



In [ ]:
# TRIF+time
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage 
    csv1 = os.path.join('data', 'HeLa', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'HeLa', 'tracking_time2.csv')
    output = os.path.join('data', 'HeLa')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution = [0.5, 1.0, 1.0], # TRIF
        img_shape = [975,910,500],    # TRIF
        spatial_shift = [[0,0,0],[0,0,0]], # 3D
        temporal_shift = [0,30],
        mode = 'temporal',  
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

In [1]:
# TRIF+space
import INTACT as integ
import os
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage 
    csv1 = os.path.join('data', 'HeLa', 'tracking_time1.csv')
    csv2 = os.path.join('data', 'HeLa', 'tracking_time2.csv')
    output = os.path.join('data', 'HeLa')

    movieInfo_new = integ.tracklets_integration(
        csv_path1=csv1,
        csv_path2=csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution = [0.5, 1.0, 1.0], # TRIF
        img_shape = [975,910,500],    # TRIF
        img_shape1 = [975,470,500],
        img_shape2 = [975,470,500],
        spatial_shift = [[0,0,0],[0,440,0]], # 3D
        temporal_shift = [0,0],
        mode = 'spatial',  
        solver = 'bb',   # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )

Start Tracklet Integration!

Step 1: Reading tracking data...W
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/TRIF/space/movieInfo_space1.pkl
Successfully converted MATLAB struct to Python dictionary and saved to /mnt/26f9605d-186a-448a-a28a-495884a29801/zqh/INTACT_experiments/TRIF/space/movieInfo_space2.pkl

[movieInfo1 after reading]
  detections: 159575
  frames range: [0, 79]
  xCoord range: [45.966, 456.733]
  yCoord range: [20.292, 470.000]
  zCoord range: [9.783, 835.944]

[movieInfo2 after reading]
  detections: 155351
  frames range: [0, 79]
  xCoord range: [33.426, 461.215]
  yCoord range: [1.000, 468.718]
  zCoord range: [7.500, 844.052]
  Reading time: 340.65 seconds

Step 2: Selecting common cells...

[movieInfo1_partial after reading]
  detections: 12258
  frames range: [0, 79]
  xCoord range: [53.341, 456.733]
  yCoord range: [118.687, 161.833]
  zCoord range: [19.233, 835.944]

[mov

KeyError: np.int64(55160)

### Application3: Multi-view stitching

In [ ]:
# multi-view
import INTACT as integ
from importlib import reload
reload(integ)
if __name__ == "__main__":
    # Example usage
    csv1 = os.path.join('data', 'FISH', 'movieInfoAll_0812_transformed.csv')
    csv2 = os.path.join('data', 'FISH', 'movieInfoAll_1014_transformed.csv')
    output = os.path.join('data', 'FISH') 

    movieInfo_new = integ.tracklets_integration(
        csv_path1 = csv1,
        csv_path2 = csv2,
        seg_indice = 'matlab',
        output_path=output,
        resolution=[4.546, 1.0, 1.0], 
        img_shape = [1837,1954,1928],    
        img_shape1 = [1837,1954,1928],
        img_shape2=[1837,1954,1928],
        spatial_shift = [[0,0,0],[0,0,0]], 
        temporal_shift = [0,0],
        mode = 'spatial',    
        solver = 'gurobi',     # 'pulp' or 'gurobi' or 'bb'
        saveSeg = False,
    )